url: http://armanb.ir
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
favicon: assets/images/myicon.png
repository: arman-borkhani/armanb.ir
github:
  username: arman-borkhani
repository: armanb.ir
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-jalali